### ISSUE TITLE
Error when running npm install

### ISSUE THREAD

**Issue by bkarakashev** [firefinchdev/whatsapp-desktop-dark#1]
![image](https://user-images.githubusercontent.com/6206509/85323714-6df95a00-b4c0-11ea-8fe4-ed972a9f806b.png)

I have resolved this issue by removing the **"resourcehacker": "4.2.51"** from the **devDependencies**.

**Comment by firefinchdev** [comment]
Are you running macOS?

**Comment by bkarakashev** [comment]
> Are you running macOS?

Yes v10.15.5

**Comment by firefinchdev** [comment]
You can remove that dependency and run. Resource hacker is for windows, that why it's failing for Mac.

**Comment by bkarakashev** [comment]
> You can remove that dependency and run. Resource hacker is for windows, that why it's failing for Mac.

This is exactly what I said I did to go around the issue 🙂
