### ISSUE TITLE
No Theme Available in WA Version 2.2025.7

### ISSUE THREAD

**Issue by vRobM** [firefinchdev/whatsapp-desktop-dark#2]
plz do the needful

No option appears in settings for "Chats" so no way to change theme.

**Comment by JVDL-1** [comment]
Same here. Did work before, but today the option for dark mode is gone. Would be great if there is a fix!

**Comment by froveda** [comment]
I'm at macos, but using this one: https://github.com/firefinchdev/whatsapp-desktop-dark#downloads worked for me for 2.2025.7. When you download, it says that is for version`2.2023.2`, but it worked for me anyway.

BTW, it is only for dark theme, it won't allow you to select other theme

**Comment by vRobM** [comment]
Doesn't work on Windows 10.

++ Rob

*About me <https://about.me/vRobM>*

**Comment by froveda** [comment]
I just tested it in windows 10, and it is working. After installing it (it took longer than in macos), I go to Configuration -> Theme (I have it in spanish so I don't know if it is the exact route in english), and I select Dark

**Comment by froveda** [comment]
Here is a screenshot:

<img width="972" alt="Screen Shot 2020-06-24 at 17 02 04" src="https://user-images.githubusercontent.com/1401741/85622173-d5d4af80-b63c-11ea-9756-0f20b165423a.png">

**Comment by vRobM** [comment]
Thank you for following up @froveda 

I tried it again and this time (yes it took a lot longer) it worked (even though it errored!

![image](https://user-images.githubusercontent.com/2704733/85627540-846bf680-b623-11ea-8cd4-70d210e67e25.png)

![image](https://user-images.githubusercontent.com/2704733/85627594-98aff380-b623-11ea-8528-79857b522430.png)

It seems it would have been easier to just copy the theme already in the app when you press the little broken circle button for My Status. ;-)
Cheers
